### ISSUE TITLE
test_weighted_median fails

### ISSUE THREAD

**Issue by wojtask** [wojtask/CormenPy#17]
Sometimes weighted_median fails tests. Find out if it's because of a bug in the algorithm or the test.

**Comment by wojtask** [comment]
```python
Error
Traceback (most recent call last):
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\test\test_chapter09\test_problem9_2.py", line 40, in test_weighted_median
    actual_weighted_median = weighted_median(array, weights, 1, array.length)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\chapter09\problem9_2.py", line 39, in weighted_median
    return weighted_median(A, w, q, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\chapter09\problem9_2.py", line 39, in weighted_median
    return weighted_median(A, w, q, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\chapter09\problem9_2.py", line 39, in weighted_median
    return weighted_median(A, w, q, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 968 more times]
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\chapter09\problem9_2.py", line 26, in weighted_median
    _select_with_weights(A, w, p, r, (p + r) // 2)
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\chapter09\problem9_2.py", line 46, in _select_with_weights
    fives = Array(A[k:min(k + 5, r)] for k in between(p, r, step=5))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\datastructures\array.py", line 13, in __init__
    self.elements = list(elements)
                    ^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\chapter09\problem9_2.py", line 46, in <genexpr>
    fives = Array(A[k:min(k + 5, r)] for k in between(p, r, step=5))
                  ~^^^^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\datastructures\array.py", line 33, in __getitem__
    return Array((self[i] for i in between(start, stop)), start=self.start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\datastructures\array.py", line 13, in __init__
    self.elements = list(elements)
                    ^^^^^^^^^^^^^^
  File "\\wsl$\Ubuntu\home\kwojtas\cormenpy\src\datastructures\array.py", line 33, in <genexpr>
    return Array((self[i] for i in between(start, stop)), start=self.start)
                  ~~~~^^^
RecursionError: maximum recursion depth exceeded
```
